title: Ito Windsor's Homepage
page-top-title: Ito Windsor
top-section-bg-text: Quantitative Finance
home-subtitle: ItoWindsor&ensp;|&ensp;Ito
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
